name: "Nain CI workflow"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cmake git nodejs npm cmocka

      - name: Compile and run tests
        run: |
          gcc -o my_tests my_tests.c -lcmocka
          ./my_tests
